version: "2"
services:
  proxy:
    build: .
    ports:
    - "80:3000"
  comments:
    build: ./comments/.
    ports:
    -  "3001:3001"
    depends_on:
    - mongo
  mediaplayer:
    build: ./mediaplayer/.
    ports:
    -  "3002:3002"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - ./db:/data/db
